# Generated by Django 4.1.5 on 2023-01-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
