# Generated by Django 4.1.5 on 2023-01-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=450),
            preserve_default=False,
        ),
    ]
